[tool.bumpversion]
current_version = "1.8.1"
commit = true
tag = true

[[tool.bumpversion.files]]
filename = "dtw/__init__.py"
search = "__version__ = '{current_version}'"
replace = "__version__ = '{new_version}'"
