[build-system]
# Minimum requirements for the build system to execute.
# PEP 508 specifications.
requires = ["setuptools", "wheel", "Cython", "numpy>1.19", "Cython>=0.29.21"]
build-backend = "setuptools.build_meta"
