[build-system]
# Minimum requirements for the build system to execute.
# PEP 508 specifications.
requires = ["setuptools", 
    "wheel",
    "Cython",
    "oldest-supported-numpy"
]

build-backend = "setuptools.build_meta"
